language: lisp

env:
    matrix:
      - LISP=sbcl
      - LISP=sbcl32
      - LISP=ccl
      - LISP=ccl32
      - LISP=ecl
      - LISP=abcl
      - LISP=clisp
      - LISP=clisp32
      # - LISP=allegro
      # - LISP=cmucl

matrix:
  allow_failures:

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - bin/fetch-configlet
  - bin/configlet .
  - cl
    - -l 'lisp-unit'
    - -l 'cl-json'
    - -f 'bin/xlisp-test.lisp'
    - -e '(when (xlisp-test:run-tests-all) (uiop:quit 4))'

# Cut and paste to run all tests locally.

# cl -l 'lisp-unit' -l 'cl-json' -f 'bin/xlisp-test.lisp' -e '(when (xlisp-test:run-tests-all) (uiop:quit 4))'

# Add a numeric argument to XLISP-TEST:RUN-TESTS-ALL between 0 and 7
# to control optional verbosity (default is 2).
