---
language: lisp

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=ecl
    - LISP=clisp
    - LISP=abcl-bin
    - LISP=allegro
    # - LISP=clasp
    # - LISP=cmu-bin

matrix:
  fast_finish: true
  allow_failures:
    - env: LISP=abcl-bin
    - env: LISP=allegro
    # - env: LISP=cmu-bin
    # - env: LISP=clasp

install:
  - curl -L 'https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh' | sh

before_script:
  - bin/fetch-configlet
  - bin/configlet lint .

script:
  - ros run -l 'bin/xlisp-test.lisp' -e '(xlisp-test:travis-build)' -q

# Cut and paste above to run all tests locally.

# Add a numeric argument to XLISP-TEST:RUN-TESTS-ALL between 0 and 7
# to control optional verbosity (default is 3).
