name: Configlet Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  configlet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Fetch configlet
      uses: exercism/github-actions/configlet-ci@main
        
    - name: Configlet Sync
      run: configlet sync --tests --docs --metadata --filepaths

    - name: Create issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/configlet-sync-issue.md
        update_existing: true
